### ISSUE TITLE
ImportError: cannot import name 'main' from 'canonical_imports.__main__'

### ISSUE THREAD

**Issue by pawamoy** [15r10nk/canonical-imports#1]
The console script is configured such that this is the script created when installing the package:

```python
#!/home/pawamoy/.local/pipx/venvs/canonical-imports/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from canonical_imports.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

This is correct. However, the contents of `__main__.py` causes an import error issue:

```python
if __name__ == "__main__":  # pragma: no cover
    from ._core import main

    main()
```

Indeed, if you add `print(__name__)` at the beginning, you'll see that when doing `from canonincal_imports.__main__ import main`, `__name__` becomes `"canonical_imports.__main__"` in this module, not just `"__main__"`. So the condition evaluates to false and the import from `_core` is not made.

I think the easiest solution is to move the import out of the condition.

(By the way, let me know if you prefer getting reports on this repo or the insiders one)

**Comment by 15r10nk** [comment]
damn

> I think the easiest solution is to move the import out of the condition.

It was there previously, but I moved it because It made the "no cover" declaration easier.

These where the only lines with no coverage. I should ban `#pragma: no cover` from my projects :see_no_evil:. 

Thank you and yes, you I would prefer when you report your issues here.

**Comment by 15r10nk** [comment]
I published version 0.1.0 which should fix your issue.

**Comment by pawamoy** [comment]
Thanks! I think you forgot to update the version in `__init__.py` :sweat_smile:

**Comment by pawamoy** [comment]
I believe this is resolved.
